// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test sending email', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Test sending email', async function() {
    await driver.get("http://localhost:8081/")
    await driver.manage().window().setRect({ width: 822, height: 843 })
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("aiman.ab.ghapar@gmail.com")
    await driver.findElement(By.id("message")).click()
    await driver.findElement(By.id("message")).sendKeys("Test email sent")
    await driver.findElement(By.css("button")).click()
    await driver.findElement(By.css("html")).click()
    await driver.close()
  })
})
