# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestsendingemail():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testsendingemail(self):
    # Test name: Test sending email
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://localhost:8081/")
    # 2 | setWindowSize | 822x843 | 
    self.driver.set_window_size(822, 843)
    # 3 | click | id=email | 
    self.driver.find_element(By.ID, "email").click()
    # 4 | type | id=email | aiman.ab.ghapar@gmail.com
    self.driver.find_element(By.ID, "email").send_keys("aiman.ab.ghapar@gmail.com")
    # 5 | click | id=message | 
    self.driver.find_element(By.ID, "message").click()
    # 6 | type | id=message | Test email sent
    self.driver.find_element(By.ID, "message").send_keys("Test email sent")
    # 7 | click | css=button | 
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    # 8 | click | css=html | 
    self.driver.find_element(By.CSS_SELECTOR, "html").click()
    # 9 | close |  | 
    self.driver.close()
  
